### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by Saboteur777**
Prevents Craft from constantly notifying about last update :)

### CODE REVIEW

**Comment by webremote** [comment]
Knew i forgot something.... thanks Saboteur777!

**Comment by Saboteur777** [comment]
At least I can help with something :) What is koen?

**Comment by webremote** [comment]
The wrong name, im sorry! Inbox showed a weird combination of your pr and the last pr, so i mixed up the names

**Comment by Saboteur777** [comment]
No probz, mate! :laughing:

**Pull request merged**
